project:
  type: website
  output-dir: _site
website:
  title: COMPUTO
  site-url: https://computo.sfds.asso.fr/
  description: A platform for computational research and reproducibility
  favicon: assets/favicon.ico
  navbar:
    background: primary
    logo-alt: Computo’s Logo
    toggle-position: right
    tools-collapse: true
    right:
    - href: index.qmd
      text: Home
    - href: about/index.qmd
      text: About
    - href: publications/index.qmd
      text: Articles
    - href: submit/index.qmd
      text: Submit
    - href: review/index.qmd
      text: Review
    - href: repos/index.qmd
      text: Repositories
    - href: board/index.qmd
      text: Staff
    - href: blog/index.qmd
      text: FAQ
    - icon: github
      href: https://github.com/computorg
    - icon: mastodon
      href: https://mathstodon.xyz/@computo
  page-footer:
    left: "\xA9 2023 Computo"
    border: false
    background: primary
    
    right:
    - text: Privacy Policy
      href: privacy.qmd
    - text: Terms of Use
      href: terms.qmd
format:
  html:
    theme:
      light: [ custom.scss, light.scss ]
      dark: [ custom.scss, dark.scss ]
    toc: true
    code-copy: true
    code-block-border-left: true
    highlight-style: github
    citations-hover: true
    footnotes-hover: true
    include-in-header:
    - text: '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.2/css/academicons.min.css">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

        '
execute:
  freeze: auto

brand: ./_brand.yml