project:
  type: website
  output-dir: _site
#  pre-render: dotnet fsi getcomputo-pub.fsx
website:
  title: COMPUTO
  site-url: https://computo.sfds.asso.fr/
  description: A platform for computational research and reproducibility
  favicon: assets/favicon.ico
  navbar:
    background: primary
    logo-alt: Computo’s Logo
    toggle-position: right
    tools-collapse: true
    right:
    - text: Home
      href: index.qmd      
    - text: About
      href: site/about.qmd      
    - text: Articles
      href: site/publications.qmd      
    - text: Authors
      href: site/guidelines-authors.qmd
    - text: Reviewers
      href: site/guidelines-reviewers.qmd
    - text: Staff
      href: site/board.qmd
    - text: FAQ
      href: blog/index.qmd      
    - icon: github
      href: https://github.com/computorg
    - icon: mastodon
      href: https://mathstodon.xyz/@computo
  page-footer:
    left: "\xA9 2023 Computo"
    border: false
    background: primary
    
    right:
    - text: Privacy Policy
      href: site/various/privacy.qmd
    - text: Terms of Use
      href: site/various/terms.qmd
    center: ""
format:
  html:
    theme:
      light: [ custom.scss, light.scss ]
      dark: [ custom.scss, dark.scss ]
    toc: true
    code-copy: true
    code-block-border-left: true
    highlight-style: github
    citations-hover: true
    footnotes-hover: true
    include-in-header:
    - text: '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.2/css/academicons.min.css">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

        '
execute:
  freeze: auto

brand: ./_brand.yml